### ISSUE TITLE
January 25 Workshop checklist

### ISSUE THREAD

**Issue by cmilica** [gitter-lab/ml-bio-workshop#65]
- [ ] look into the pyinstaller package https://www.pyinstaller.org/

- [ ] make logo/icons according to [this issue](https://github.com/carpentries/lesson-example/issues/278)

- [ ] icons to be added to the website or removed altogether

- [ ] add approcpriate licences

- [ ] add file zip command to Makefile

- [ ]  increase the default max iterations for logistic regression. Currently, default is 500

- [ ] either add the advance settings for the hyperparameters or grey out certain ones. Talk to Milica about which hyperparameters go in the advanced settings. 

- [ ] check IRB university guidelines for the pre and post-surveys.

- [ ] create a pre and post-survey.

- [ ] finalize code of conduct

- [ ] edit contributions

**Comment by agitter** [comment]
I added "edit T cell datasets to be active or inactive instead of activated or quiescent".  We can discuss that change decide whether it is better to avoid jargon or be more biologically correct.

**Comment by agitter** [comment]
Pull request https://github.com/gitter-lab/ml4bio/pull/21 edits the logistic regression default iterations.  We'll have to make another software release if we want to use this in the next workshop though.

**Comment by agitter** [comment]
Regarding the surveys, Debora and Beth pointed me to https://uwsc.wisc.edu/  They can help us design a more formal survey that would eventually support collecting data that could be used in research.

For the upcoming workshop, we'll continue using the existing informal survey.  I'll check the box once I create the survey in qualtrics.

**Comment by cmilica** [comment]
Sounds good!

**Comment by agitter** [comment]
I checked the boxes that were addressed by #69

**Comment by agitter** [comment]
We can add back a logo image by using the machine learning images from the Noun Project that are in the ml4bio software: https://github.com/gitter-lab/ml4bio/tree/master/ml4bio/icons
